# Generated by Django 3.2.9 on 2021-11-14 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Property',
            new_name='Problem',
        ),
        migrations.RenameField(
            model_name='decidiability',
            old_name='property',
            new_name='problem',
        ),
    ]
