# Generated by Django 3.2.9 on 2021-11-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20211114_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='full_name',
            field=models.CharField(default='', max_length=60),
        ),
    ]
